/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.MenuAdministradorControl;

/**
 *
 * @author Aluno
 */
public class MenuAdministradorView extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministradorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbt_Administrador = new javax.swing.JButton();
        jbt_Categoria = new javax.swing.JButton();
        jbt_Produto = new javax.swing.JButton();
        jbt_Cliente = new javax.swing.JButton();
        jbt_Mensagem = new javax.swing.JButton();
        jbt_Cliente1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbt_Cliente2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Bem-vindo, ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome do Usuário");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbt_Administrador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Administrador.setText("Administradores");
        jbt_Administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_AdministradorActionPerformed(evt);
            }
        });

        jbt_Categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Categoria.setText("Categorias");
        jbt_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_CategoriaActionPerformed(evt);
            }
        });

        jbt_Produto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Produto.setText("Produtos");
        jbt_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_ProdutoActionPerformed(evt);
            }
        });

        jbt_Cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Cliente.setText("Clientes");
        jbt_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_ClienteActionPerformed(evt);
            }
        });

        jbt_Mensagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Mensagem.setText("Mensagens");
        jbt_Mensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_MensagemActionPerformed(evt);
            }
        });

        jbt_Cliente1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Cliente1.setText("Sair");
        jbt_Cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_Cliente1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Bem-vindo! ");

        jbt_Cliente2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Cliente2.setText("Compras");
        jbt_Cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_Cliente2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbt_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbt_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbt_Mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbt_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbt_Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbt_Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel3)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jbt_Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_AdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_AdministradorActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuAdministradorControl.telaAdministrador();
        
    }//GEN-LAST:event_jbt_AdministradorActionPerformed

    private void jbt_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_ProdutoActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuAdministradorControl.telaProduto();
    }//GEN-LAST:event_jbt_ProdutoActionPerformed

    private void jbt_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_ClienteActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuAdministradorControl.telaCliente();
    }//GEN-LAST:event_jbt_ClienteActionPerformed

    private void jbt_MensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_MensagemActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuAdministradorControl.TelaMensagem();
    }//GEN-LAST:event_jbt_MensagemActionPerformed

    private void jbt_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_CategoriaActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuAdministradorControl.telaCategoria();
    }//GEN-LAST:event_jbt_CategoriaActionPerformed

    private void jbt_Cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_Cliente1ActionPerformed
       dispose();
    }//GEN-LAST:event_jbt_Cliente1ActionPerformed

    private void jbt_Cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_Cliente2ActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuAdministradorControl.TelaListarCompra();
    }//GEN-LAST:event_jbt_Cliente2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministradorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbt_Administrador;
    private javax.swing.JButton jbt_Categoria;
    private javax.swing.JButton jbt_Cliente;
    private javax.swing.JButton jbt_Cliente1;
    private javax.swing.JButton jbt_Cliente2;
    private javax.swing.JButton jbt_Mensagem;
    private javax.swing.JButton jbt_Produto;
    // End of variables declaration//GEN-END:variables
}
