/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AdministradorControl;
import controller.CategoriaControl;
import controller.MensagemControl;
import tableModel.CategoriaTM;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CategoriaView extends javax.swing.JFrame {
    CategoriaTM modelo; 
    public void loadTable(){
       modelo = new CategoriaTM(CategoriaControl.getsCategorias());
       jtb_Categoria.setModel(modelo);
       
       jtb_Categoria.getColumnModel().getColumn(0).setPreferredWidth(10);
       jtb_Categoria.getColumnModel().getColumn(1).setPreferredWidth(100);
       
    } 
    /**
     * Creates new form CategoriaView
     */
    public CategoriaView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbt_Voltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbt_Salvar = new javax.swing.JButton();
        jtf_Id = new javax.swing.JTextField();
        jtf_Tipo = new javax.swing.JTextField();
        Tipo = new javax.swing.JLabel();
        jlbl_Id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Categoria = new javax.swing.JTable();
        jbt_Excluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbt_Voltar1 = new javax.swing.JButton();

        jbt_Voltar.setText("Voltar");
        jbt_Voltar.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));

        jbt_Salvar.setText("Salvar");
        jbt_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_SalvarActionPerformed(evt);
            }
        });

        jtf_Id.setEnabled(false);

        Tipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tipo.setText("Tipo");

        jlbl_Id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbl_Id.setText("Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tipo)
                            .addComponent(jlbl_Id))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(jtf_Id))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_Id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo)
                    .addComponent(jtf_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtb_Categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_CategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_Categoria);
        jtb_Categoria.getAccessibleContext().setAccessibleName("jtb_cat");

        jbt_Excluir.setText("Excluir");
        jbt_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_ExcluirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("Lista de Categorias");

        jbt_Voltar1.setText("Voltar");
        jbt_Voltar1.setToolTipText("");
        jbt_Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_Voltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(204, 204, 204))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbt_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(86, 86, 86))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt_Voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jbt_Voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_SalvarActionPerformed
        // TODO add your handling code here:
        
        int i = jtb_Categoria.getSelectedRow();
        int ver = 0;
       if(jtb_Categoria.isRowSelected(i))
       {
           ver = CategoriaControl.salvarCategoria(jtb_Categoria.getSelectedRow(),jtf_Id.getText(),jtf_Tipo.getText());
       }
       else
       {
           ver = CategoriaControl.salvarCategoria(jtb_Categoria.getSelectedRow(),String.valueOf(CategoriaControl.novoId()+1),jtf_Tipo.getText());
       }
        
       if(ver==1)
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else if(ver==0)
        {
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        }
           this.loadTable();
    }//GEN-LAST:event_jbt_SalvarActionPerformed
    
    private void jbt_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_ExcluirActionPerformed
        // TODO add your handling code here:
        CategoriaControl.excluirCategoria(jtb_Categoria.getSelectedRow());
        jtf_Id.setText("");
            jtf_Tipo.setText("");
           this.loadTable();
           
    }//GEN-LAST:event_jbt_ExcluirActionPerformed

    private void jtb_CategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_CategoriaMouseClicked
         int index = jtb_Categoria.getSelectedRow();
        if(index >= 0 && index<modelo.getRowCount()){
            String temp[] = modelo.getAluno(index);
            jtf_Id.setText(temp[0]);
            jtf_Tipo.setText(temp[1]);
        }    
        //Botoes(true, true, true, false, false);
    }//GEN-LAST:event_jtb_CategoriaMouseClicked

    private void jbt_Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_Voltar1ActionPerformed
      dispose();
        MenuAdministradorView menu = new MenuAdministradorView();
        menu.setVisible(true);
    }//GEN-LAST:event_jbt_Voltar1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        String asd = jtf_Id.getText();
        if(asd.equals(""))
        {
            //System.out.println("Limpo");
            
        }else{   
            //System.out.println("nao Limpo");
            jtb_Categoria.clearSelection();
            jtf_Id.setText("");
            jtf_Tipo.setText("");
        }
    }//GEN-LAST:event_formMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoriaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_Excluir;
    private javax.swing.JButton jbt_Salvar;
    private javax.swing.JButton jbt_Voltar;
    private javax.swing.JButton jbt_Voltar1;
    private javax.swing.JLabel jlbl_Id;
    private javax.swing.JTable jtb_Categoria;
    private javax.swing.JTextField jtf_Id;
    private javax.swing.JTextField jtf_Tipo;
    // End of variables declaration//GEN-END:variables
}
