/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.ListaCompraControl;
import tableModel.ListarCompraTM;

/**
 *
 * @author Aluno
 */
public class ListaCompraView extends javax.swing.JFrame {
    ListarCompraTM modelo;
    
    public void loadTable(){
        modelo = new ListarCompraTM(ListaCompraControl.getCompras());
        jtb_Compras.setModel(modelo);
            

        jtb_Compras.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtb_Compras.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtb_Compras.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtb_Compras.getColumnModel().getColumn(3).setPreferredWidth(150);
        jtb_Compras.getColumnModel().getColumn(4).setPreferredWidth(150);
    }
    
    /**
     * Creates new form ListaCompraView
     */
    public ListaCompraView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStatus = new javax.swing.JRadioButton();
        jbt_Salvar = new javax.swing.JButton();
        jbt_Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Compras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jStatus.setText("Atualizar Status da Mensagem");
        jStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStatusActionPerformed(evt);
            }
        });

        jbt_Salvar.setText("Salvar");
        jbt_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_SalvarActionPerformed(evt);
            }
        });

        jbt_Voltar.setText("Voltar");
        jbt_Voltar.setToolTipText("");
        jbt_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_VoltarActionPerformed(evt);
            }
        });

        jtb_Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_ComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_Compras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbt_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jStatus)))
                    .addContainerGap(229, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jbt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(286, 286, 286)
                    .addComponent(jStatus)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                    .addComponent(jbt_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStatusActionPerformed

    private void jbt_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_SalvarActionPerformed
        // TODO add your handling code here:
        int i = jtb_Compras.getSelectedRow();
           if(jStatus.isSelected())
           {
               ListaCompraControl.atualizarStatus(i,true);
               
           }
           else
           {
               //MensagemControl.salvarMsg(jtb_Msg.getSelectedRow(),jtb_Msg.getModel().getValueAt(i, 0).toString(),jtb_Msg.getModel().getValueAt(i, 1).toString(),false);
           }
        //String tempId = jtb_Admin.getModel().getValueAt(jtb_Admin.getRowCount(),0));
//        //jtf_Id.setText();
//        //jtf_Id.setText();
//
//        //jtf_Senha.setText("");

        //Botoes(true, false, false, true, true);
        //this.loadTable();
        this.loadTable();
    }//GEN-LAST:event_jbt_SalvarActionPerformed

    private void jtb_ComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_ComprasMouseClicked
        //TODO add your handling code here:
        int index = jtb_Compras.getSelectedRow();
        if(index >= 0 && index<modelo.getRowCount()){
            String temp[] = modelo.getAluno(index);
            if(temp[4].equals("Pendente"))
            {
                jStatus.setSelected(false);
            }
            else
            {
                jStatus.setSelected(true);
            }
            //jtf_Id.setText(temp[0]);
            //jTxt.setText(temp[1]);
            //jtf_Senha.setText(temp[2]);
        }
//        Botoes(true, true, true, true, false);
    }//GEN-LAST:event_jtb_ComprasMouseClicked

    private void jbt_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_VoltarActionPerformed
        // TODO add your handling code here:
        MenuAdministradorView MAw = new MenuAdministradorView();
        MAw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbt_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCompraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCompraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCompraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCompraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaCompraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jStatus;
    private javax.swing.JButton jbt_Salvar;
    private javax.swing.JButton jbt_Voltar;
    private javax.swing.JTable jtb_Compras;
    // End of variables declaration//GEN-END:variables
}
