/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MensagemControl;
import tableModel.MensagemTM;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class MensagemView extends javax.swing.JFrame {
    
    MensagemTM modelo; 
    public void loadTable(){
       modelo = new MensagemTM(MensagemControl.getMsg());
       jtb_Msg.setModel(modelo);

        jtb_Msg.getColumnModel().getColumn(0).setPreferredWidth(10);
        jtb_Msg.getColumnModel().getColumn(1).setPreferredWidth(200);
        jtb_Msg.getColumnModel().getColumn(2).setPreferredWidth(10);
       
    } 
    /**
     * Creates new form MensagemView
     */
    public MensagemView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Msg = new javax.swing.JTable();
        jStatus = new javax.swing.JRadioButton();
        jbt_Salvar = new javax.swing.JButton();
        jbt_Voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Lista de Mensagens");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtb_Msg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_MsgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_Msg);

        jStatus.setText("Atualizar Status da Mensagem");
        jStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStatusActionPerformed(evt);
            }
        });

        jbt_Salvar.setText("Salvar");
        jbt_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_SalvarActionPerformed(evt);
            }
        });

        jbt_Voltar.setText("Voltar");
        jbt_Voltar.setToolTipText("");
        jbt_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_VoltarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Lista de Mensagens");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbt_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void Botoes(boolean N, boolean E, boolean R, boolean S, boolean C){
        jbt_Salvar.setEnabled(S);    
    }
    
    private void jtb_MsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_MsgMouseClicked
        //TODO add your handling code here:
        int index = jtb_Msg.getSelectedRow();
        if(index >= 0 && index<modelo.getRowCount()){
            String temp[] = modelo.getAluno(index);
            if(temp[2].equals("Pendente"))
            {
                jStatus.setSelected(false);
            }
            else
            {
                jStatus.setSelected(true);
            }
            //jtf_Id.setText(temp[0]);
            //jTxt.setText(temp[1]);
            //jtf_Senha.setText(temp[2]);
        }
        Botoes(true, true, true, true, false);
    }//GEN-LAST:event_jtb_MsgMouseClicked

    private void jbt_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_SalvarActionPerformed
        // TODO add your handling code here:
        int i = jtb_Msg.getSelectedRow();
        int ver = 0;
        if(jtb_Msg.isRowSelected(i))
        {
           if(jStatus.isSelected())
           {
               ver = MensagemControl.salvarMsg(jtb_Msg.getSelectedRow(),jtb_Msg.getModel().getValueAt(i, 0).toString(),jtb_Msg.getModel().getValueAt(i, 1).toString(),true);
           }
           else
           {
              ver = MensagemControl.salvarMsg(jtb_Msg.getSelectedRow(),jtb_Msg.getModel().getValueAt(i, 0).toString(),jtb_Msg.getModel().getValueAt(i, 1).toString(),false);
           }
           if(ver==1)
            {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            }
            else if(ver==0)
            {
                JOptionPane.showMessageDialog(null, "Mensagem enviado com sucesso!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione uma coluna antes de atualizar um status!");
        }
           
        //String tempId = jtb_Admin.getModel().getValueAt(jtb_Admin.getRowCount(),0));
        //jtf_Id.setText();
        //jtf_Id.setText();

        //jtf_Senha.setText("");

        Botoes(true, false, false, true, true);
        this.loadTable();
    }//GEN-LAST:event_jbt_SalvarActionPerformed

    private void jStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStatusActionPerformed
                    // TODO add your handling code here:
    }//GEN-LAST:event_jStatusActionPerformed

    private void jbt_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_VoltarActionPerformed
        dispose();
        MenuAdministradorView menu = new MenuAdministradorView();
        menu.setVisible(true);
    }//GEN-LAST:event_jbt_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MensagemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jStatus;
    private javax.swing.JButton jbt_Salvar;
    private javax.swing.JButton jbt_Voltar;
    private javax.swing.JTable jtb_Msg;
    // End of variables declaration//GEN-END:variables
}
