/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MenuClienteControl;
import model.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Philipe
 */
public class MenuClienteView extends javax.swing.JFrame {
    MenuClienteControl MC = new MenuClienteControl();
    int indexCliente = -1;
    /**
     * Creates new form MenuClienteView
     */
    public MenuClienteView() {
        initComponents();
        System.out.println("iD Cliente:"+MC.indexCliente);
    }
    
    public MenuClienteView(int i) {
        indexCliente = i;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbt_Compra = new javax.swing.JButton();
        jbt_Mensagem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbt_Compra2 = new javax.swing.JButton();
        jbt_Editar = new javax.swing.JButton();
        jbt_Excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbt_Compra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Compra.setText("Produtos");
        jbt_Compra.setToolTipText("");
        jbt_Compra.setPreferredSize(new java.awt.Dimension(83, 23));
        jbt_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_CompraActionPerformed(evt);
            }
        });

        jbt_Mensagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Mensagem.setText("Enviar Mensagem para Administrador");
        jbt_Mensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_MensagemActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Compras Realizadas");
        jButton1.setMaximumSize(new java.awt.Dimension(83, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(83, 23));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Bem-vindo! ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbt_Compra2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_Compra2.setText("Sair");
        jbt_Compra2.setToolTipText("");
        jbt_Compra2.setPreferredSize(new java.awt.Dimension(83, 23));
        jbt_Compra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_Compra2ActionPerformed(evt);
            }
        });

        jbt_Editar.setText("Editar");
        jbt_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_EditarActionPerformed(evt);
            }
        });

        jbt_Excluir.setText("Excluir");
        jbt_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbt_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_Compra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_Mensagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_Compra2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_Editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jbt_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbt_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbt_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbt_Compra2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_MensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_MensagemActionPerformed
        // TODO add your handling code here:
        dispose();
        MC.bt_Mensagem();
    }//GEN-LAST:event_jbt_MensagemActionPerformed

    private void jbt_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_CompraActionPerformed
        // TODO add your handling code here:
        dispose();
        MC.bt_Compra();
       
    }//GEN-LAST:event_jbt_CompraActionPerformed

    private void jbt_Compra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_Compra2ActionPerformed
       dispose();
    }//GEN-LAST:event_jbt_Compra2ActionPerformed

    private void jbt_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_EditarActionPerformed
        // TODO add your handling code here:
        MC.bt_Editar();
    }//GEN-LAST:event_jbt_EditarActionPerformed

    private void jbt_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_ExcluirActionPerformed
        // TODO add your handling code here:
        MenuClienteControl me = new MenuClienteControl(indexCliente);
        if(me.bt_Excluir()){
            this.dispose();
        }
        
    }//GEN-LAST:event_jbt_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbt_Compra;
    private javax.swing.JButton jbt_Compra2;
    private javax.swing.JButton jbt_Editar;
    private javax.swing.JButton jbt_Excluir;
    private javax.swing.JButton jbt_Mensagem;
    // End of variables declaration//GEN-END:variables
}
