/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.AdministradorControl;
import controller.CategoriaControl;
import controller.ProdutoControl;
import tableModel.ProdutoTM;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Aluno
 */
public class ProdutoView extends javax.swing.JFrame {
    ProdutoTM modelo; 
    public void loadTable(){
       modelo = new ProdutoTM(ProdutoControl.getProdutos());
       jtb_Prod.setModel(modelo);

        jtb_Prod.getColumnModel().getColumn(0).setPreferredWidth(30);
        jtb_Prod.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtb_Prod.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtb_Prod.getColumnModel().getColumn(3).setPreferredWidth(200);
        jtb_Prod.getColumnModel().getColumn(4).setPreferredWidth(250);
    } 
    /**
     * Creates new form TelaProduto
     */
    public ProdutoView() {
        initComponents();
        carregarComboB1();
        loadTable();
    }
    
    
    public void carregarComboB1(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        //ArrayList<>
        
        for(String a:ProdutoControl.getTipos()){
            model.addElement(a.toString());
        }
        jcb_tipos.setModel(model);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jbt_Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Prod = new javax.swing.JTable();
        jbt_Excluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_Id = new javax.swing.JTextField();
        jtf_Nome1 = new javax.swing.JTextField();
        jtf_Preco = new javax.swing.JTextField();
        jbt_Salvar1 = new javax.swing.JButton();
        jbt_Cancelar1 = new javax.swing.JButton();
        jtf_Quant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcb_tipos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Lista de Mensagens");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jbt_Voltar.setText("Voltar");
        jbt_Voltar.setToolTipText("");
        jbt_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_VoltarActionPerformed(evt);
            }
        });

        jtb_Prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_ProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_Prod);

        jbt_Excluir.setText("Excluir");
        jbt_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_ExcluirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Preço");

        jtf_Id.setEnabled(false);

        jbt_Salvar1.setText("Salvar");
        jbt_Salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_Salvar1ActionPerformed(evt);
            }
        });

        jbt_Cancelar1.setText("Cancelar");

        jtf_Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_QuantActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade");

        jcb_tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tiposActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(299, 299, 299))
                            .addComponent(jbt_Salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Preco)
                            .addComponent(jcb_tipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_Quant)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbt_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcb_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_Salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("Lista de Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbt_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbt_Excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel5)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void Botoes(boolean N, boolean E, boolean R, boolean S, boolean C){
        //jbt_Novo.setEnabled(N);
        //jbt_Editar.setEnabled(E);
        jbt_Excluir.setEnabled(R);
        jbt_Salvar1.setEnabled(S);
        jbt_Cancelar1.setEnabled(C);        
    }
    
    private void jtb_ProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_ProdMouseClicked
        //TODO add your handling code here:
        int index = jtb_Prod.getSelectedRow();
        if(index >= 0 && index<modelo.getRowCount()){
            String temp[] = modelo.getAluno(index);
            jtf_Id.setText(temp[0]);
            jtf_Nome1.setText(temp[1]);
            jtf_Quant.setText(temp[4]);
            jtf_Preco.setText(temp[2]);
        }
        //Botoes(true, true, true, false, false);
    }//GEN-LAST:event_jtb_ProdMouseClicked

    private void jbt_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_ExcluirActionPerformed
        // TODO add your handling code here:
        ProdutoControl.excluirProduto(jtb_Prod.getSelectedRow());
        jtf_Nome1.setText("");
        jtf_Preco.setText("");
        jtf_Quant.setText("");
        jtf_Id.setText("");
        this.loadTable();
    }//GEN-LAST:event_jbt_ExcluirActionPerformed

    private void jbt_Salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_Salvar1ActionPerformed
        // TODO add your handling code here:
        int i = jtb_Prod.getSelectedRow();
        int ver = 0;
        if(jtb_Prod.isRowSelected(i))
        {
           ProdutoControl.salvarProduto(jtb_Prod.getSelectedRow(),jtf_Id.getText(),jtf_Nome1.getText(),jtf_Preco.getText(), String.valueOf(jcb_tipos.getSelectedItem()),jtf_Quant.getText());
        }
        else
        {
            ver = ProdutoControl.salvarProduto(jtb_Prod.getSelectedRow(),String.valueOf(ProdutoControl.novoId()+1),jtf_Nome1.getText(),jtf_Preco.getText(),String.valueOf(jcb_tipos.getSelectedItem()),jtf_Quant.getText());
        }
        
        
        
        switch (ver) {
            case 1:
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
                break;
            case 0:
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Dados inseridos inválidos!");
                break;
            default:
                break;
        }
        jtf_Nome1.setText("");
        jtf_Preco.setText("");
        jtf_Quant.setText("");

        //Botoes(true, false, false, true, true);
        this.loadTable();
    }//GEN-LAST:event_jbt_Salvar1ActionPerformed

    private void jtf_QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_QuantActionPerformed

    private void jcb_tiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tiposActionPerformed

    private void jbt_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_VoltarActionPerformed
       dispose();
        MenuAdministradorView menu = new MenuAdministradorView();
        menu.setVisible(true);
    }//GEN-LAST:event_jbt_VoltarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        String asd = jtf_Id.getText();
        if(asd.equals(""))
        {
            //System.out.println("Limpo");
            
        }else{   
            //System.out.println("nao Limpo");
            jtb_Prod.clearSelection();
            jtf_Id.setText("");
            jtf_Nome1.setText("");
            jtf_Quant.setText("");
            jtf_Preco.setText("");
        }
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_Cancelar1;
    private javax.swing.JButton jbt_Excluir;
    private javax.swing.JButton jbt_Salvar1;
    private javax.swing.JButton jbt_Voltar;
    private javax.swing.JComboBox<String> jcb_tipos;
    private javax.swing.JTable jtb_Prod;
    private javax.swing.JTextField jtf_Id;
    private javax.swing.JTextField jtf_Nome1;
    private javax.swing.JTextField jtf_Preco;
    private javax.swing.JTextField jtf_Quant;
    // End of variables declaration//GEN-END:variables
}
